"""All-endpoint provenance, training isolation, post-selection scores and launch."""

import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest

from autoformalism.benchmarks.audited_release import read_seal, seal
from autoformalism.fitting import confidence_campaign as campaign
from autoformalism.fitting import confidence_checks as checks
from autoformalism.fitting import larger_coupled_campaign as source
from autoformalism.fitting import public_fitting as public


@pytest.fixture(scope="module")
def exported(tmp_path_factory):
    root = tmp_path_factory.mktemp("confidence-export")
    inputs = root / "source-input.json"
    source.controls.export_inputs(inputs)
    # Unit fixtures are generated by the local numerical libraries. Their exact
    # floating-point bytes need not match the frozen, portable M18 export.
    patch = pytest.MonkeyPatch()
    patch.setattr(campaign, "SOURCE_INPUTS", public.content_sha256(read_seal(inputs)))
    source.prepare(root / "source", inputs, source.PolishingPolicy())
    plan, data = source.verify(root / "source")
    rows = []
    for task in plan["tasks"]:
        parameters = data["commons"][task["common"]]["start"]
        backend = {"selected": {"parameters": parameters}}
        seal(root / "source" / "results" / task["task_id"] / "backend.json", backend)
        rows.append(
            {
                **task,
                "backend_sha256": public.content_sha256(backend),
                "selected": backend["selected"],
                "fit_seconds": 10.0,
                "evaluation": {},
            }
        )
    public._write(
        root / "source" / "summary.json",
        {
            "plan_sha256": public.content_sha256(plan),
            "status": "complete",
            "rows": rows,
        },
    )
    output = root / "export.json"
    campaign.export(root / "source", output)
    yield output
    patch.undo()


def test_roster_freeze_and_training_boundary(exported, tmp_path):
    assert (
        campaign.prepare(tmp_path, exported, campaign.ConfidencePolicy())["tasks"] == 24
    )
    plan, data = campaign.verify(tmp_path)
    problem = campaign.training_problem(data, data["endpoints"][0])
    assert problem.training.name == "train"
    assert "reference_parameters" not in problem.model_dump()
    for case in data["data"]["cases"].values():
        case["reference_parameters"] = {"poison": "not for training"}
        case["validation"] = {"poison": "not for training"}
    assert campaign.training_problem(data, data["endpoints"][0]) == problem
    assert campaign.report(tmp_path)["recorded"] == 0
    with pytest.raises(ValueError, match="sealed artifact differs"):
        campaign.prepare(tmp_path, exported, campaign.ConfidencePolicy(restart_calls=5))
    assert len(plan["tasks"]) == 24


def test_bad_source_and_changed_vector_rejected(exported, tmp_path):
    data = read_seal(exported)
    data["data"]["cases"]["linear3"]["training"]["rows"][0]["targets"]["y"][0] += 1
    seal(tmp_path / "bad.json", data)
    with pytest.raises(ValueError, match="changed inputs"):
        campaign.prepare(
            tmp_path / "run", tmp_path / "bad.json", campaign.ConfidencePolicy()
        )
    problem = campaign.training_problem(
        read_seal(exported), read_seal(exported)["endpoints"][0]
    )
    bad = problem.model_copy(
        update={"incumbent": dict(problem.incumbent) | {"invented": 1.0}}
    )
    with pytest.raises(ValueError, match="incomplete parameter"):
        checks.Rollouts(bad, campaign.ConfidencePolicy())


def test_reference_scoring_after_seal_and_resume(exported, tmp_path, monkeypatch):
    campaign.prepare(tmp_path, exported, campaign.ConfidencePolicy())
    calls = []

    def fit(problem, policy, folder):
        selected = {"parameters": dict(problem.incumbent)}
        return {
            "status": "complete",
            "selected": selected,
            "after_reliability": selected,
            "confidence": {"level": "search_incomplete"},
            "cost_complete": True,
        }

    def evaluation(folder, data, base, parameters, seconds):
        assert (folder.parent / "backend.json").exists()
        calls.append(folder.name)
        return {"status": "complete", "coefficients_recovered": False}

    monkeypatch.setattr(campaign.confidence_fit, "run", fit)
    monkeypatch.setattr(campaign.screening_replay, "_evaluation", evaluation)
    value = campaign.run_task(tmp_path, 0)
    assert campaign.run_task(tmp_path, 0) == value and len(calls) == 2
    assert campaign.report(tmp_path)["recorded"] == 1
    with pytest.raises(ValueError, match="unknown task"):
        campaign.run_task(tmp_path, -1)


def test_numerical_derivative_includes_initials(exported):
    from time import monotonic

    import numpy as np

    data = read_seal(exported)
    endpoint = next(e for e in data["endpoints"] if e["common"] == "linear3_s0")
    oracle = checks.Rollouts(
        campaign.training_problem(data, endpoint), campaign.ConfidencePolicy()
    )
    x = oracle.vector(endpoint["parameters"])
    r, j = oracle.evaluate(x, monotonic() + 20)
    direction = np.arange(1, len(x) + 1, dtype=float)
    direction /= np.linalg.norm(direction)
    h = 1e-4
    plus, _ = oracle.evaluate(x + h * direction, monotonic() + 20, jacobian=False)
    minus, _ = oracle.evaluate(x - h * direction, monotonic() + 20, jacobian=False)
    assert np.allclose(j @ direction, (plus - minus) / (2 * h), atol=1e-7, rtol=1e-5)
    assert len(r) == 651


def test_submission_idempotent_and_one_hour(exported, tmp_path, monkeypatch):
    from scripts import submit_phase_c_fitting_confidence as submit
    from scripts import submit_phase_c_generic_recovery as scheduler

    monkeypatch.setenv("AF_PYTHON", sys.executable)
    monkeypatch.setattr(
        scheduler.subprocess, "check_output", lambda *a, **k: "revision\n"
    )
    calls = []

    def sbatch(argv, **kwargs):
        calls.append(argv)
        return SimpleNamespace(returncode=0, stdout=str(100 + len(calls)), stderr="")

    monkeypatch.setattr(scheduler.subprocess, "run", sbatch)
    args = {"account": "test", "concurrency": 6, "inputs": exported}
    config = Path("configs/phase_c_fitting_confidence_v1.json")
    first = submit.submit(tmp_path, config, **args)
    assert "--array=0-23%6" in calls[1] and "--time=01:00:00" in calls[1]
    assert first == submit.submit(tmp_path, config, **args) and len(calls) == 3


def test_shell_syntax():
    for kind in ("run", "submit", "inspect"):
        subprocess.run(
            ["bash", "-n", f"scripts/hpc/{kind}_phase_c_fitting_confidence_delta.sh"],
            check=True,
        )
