"""Scientific-judge fact extraction and deterministic aggregation."""

from autoformalism.judging.hybrid import (
    ATOMIC_EVIDENCE_SCHEMA_VERSION,
    MODEL_SEMANTIC_STRUCTURAL_FACTS_SCHEMA_VERSION,
    STRUCTURAL_FACTS_SCHEMA_VERSION,
    AtomicEvidencePlan,
    HybridScoringConfig,
    atomic_candidate_context,
    atomic_findings_payload,
    atomic_role_compatibility_assessments,
    build_atomic_evidence_plan,
    build_group_registry,
    candidate_claims,
    deterministic_pair_assessments,
    extract_public_requirements,
    merge_atomic_assessments,
    question_consensus,
    require_deterministic_orientation_consensus,
    reverse_hybrid_result,
    reverse_paired_assessments,
    score_hybrid_pair,
    semantic_absolute_units,
    structural_facts,
)
from autoformalism.judging.target_completeness import (
    fail_dominant_verdict,
    paired_target_question_consensus,
)

__all__ = [
    "ATOMIC_EVIDENCE_SCHEMA_VERSION",
    "MODEL_SEMANTIC_STRUCTURAL_FACTS_SCHEMA_VERSION",
    "STRUCTURAL_FACTS_SCHEMA_VERSION",
    "AtomicEvidencePlan",
    "HybridScoringConfig",
    "atomic_candidate_context",
    "atomic_findings_payload",
    "atomic_role_compatibility_assessments",
    "build_atomic_evidence_plan",
    "build_group_registry",
    "candidate_claims",
    "deterministic_pair_assessments",
    "extract_public_requirements",
    "fail_dominant_verdict",
    "merge_atomic_assessments",
    "paired_target_question_consensus",
    "question_consensus",
    "require_deterministic_orientation_consensus",
    "reverse_hybrid_result",
    "reverse_paired_assessments",
    "score_hybrid_pair",
    "semantic_absolute_units",
    "structural_facts",
]
