"""Local shared-process checks and concrete topology editing instructions."""

from collections import Counter

from autoformalism.schemas.staged_topology import PublicScientificBrief
from autoformalism.search import construction_ledger as ledger
from autoformalism.search.signed_processes import SignedProcess

POLICY = "minimal-stage-checks-1"
IDENTIFIERS = """In equations, name is the EXACT generated-variable identifier,
not a derivative label. For a differential variable named Gp, return
{\"name\":\"Gp\",\"terms\":[...]}, not name=\"dGp_dt\". Its declared type already
makes this the topology of d(Gp)/dt. Use the same exact identifiers in process uses.
If the name is G_p instead, preserve G_p exactly; do not rename variables."""
EMPTY_ORDINARY = """Shared-process uses are already inserted by the runtime. If they
supply all contributions for Gp, explicitly return {\"name\":\"Gp\",\"terms\":[]}.
This declares no additional ordinary contributions; it keeps all shared uses.
Omitting Gp means no edit and does not close its pending ordinary topology.
Do not add a term containing the shared processes merely to restate the balance."""
SHARED_INSTRUCTION = """A receiver must be generated by this model. A supplied
observed trajectory can drive a process but has no generated equation to receive
one. To model an observed quantity instead, explicitly declare its type in
variables; it will need its own topology. External inputs remain supplied.
Before finishing, resolve the displayed local process errors. Unknown future
references and assembled pathways are checked after the complete topology."""


def shared_checklist(brief: PublicScientificBrief, draft: ledger.Draft) -> dict:
    """Check present declarations, without requiring future ordinary topology.

    The signed-use validator is the same as final acceptance. Single-consumer
    influences retain their existing legality as named local contributions; they
    are reported separately and never counted as shared laws.
    """
    public = {v.name: v.data_role for v in brief.public_variables}
    generated = {v.name for v in draft.variables} | {p.name for p in draft.processes}
    items, processes = [], []
    for process in draft.processes:
        names = [u.target for u in process.uses]
        receivers = sorted(set(names))
        errors = []
        try:
            SignedProcess.model_validate(process.model_dump())
        except ValueError:
            duplicates = sorted(n for n, count in Counter(names).items() if count > 1)
            if duplicates:
                errors.append(
                    {
                        "code": "duplicate_receiver",
                        "receivers": duplicates,
                        "action": "List each receiving variable once per process. "
                        "Opposite signs on the same variable are not two receivers.",
                    }
                )
            if process.kind == "transfer" and (
                len(process.uses) != 2
                or len(receivers) != 2
                or {u.sign for u in process.uses} != {"positive", "negative"}
            ):
                errors.append(
                    {
                        "code": "transfer_signs",
                        "action": "For a pairwise internal transfer, choose two "
                        "distinct receivers with opposite signs. Otherwise revise "
                        "kind to influence, or remove the declaration and later "
                        "describe ordinary contributions. Do not invent a receiver "
                        "or flip a sign solely to pass the check.",
                    }
                )
        for name in receivers:
            if name in public and name not in generated:
                errors.append(
                    {
                        "code": "supplied_receiver",
                        "receiver": name,
                        "public_role": public[name],
                        "action": "This channel is supplied: its values can be "
                        "RHS drivers, but it has no generated equation to receive "
                        "a contribution. Correct or remove this process use."
                        + (
                            " If you intend to generate this observed quantity, "
                            "explicitly declare it in variables and later provide "
                            "its topology; the runtime will not choose for you."
                            if public[name] in {"auxiliary", "target"}
                            else " External inputs, covariates and time cannot be "
                            "redeclared as generated receivers."
                        ),
                    }
                )
        for error in errors:
            items.append(
                {
                    "id": f"{process.name}:{error['code']}:"
                    + error.get("receiver", ""),
                    "process": process.name,
                    "status": "inconsistent",
                    **error,
                }
            )
        unresolved = sorted(
            (set(process.depends_on) | set(names)) - generated - public.keys()
        )
        processes.append(
            {
                "name": process.name,
                "kind": process.kind,
                "receivers": receivers,
                "consumer_count": len(receivers),
                "scope": "shared" if len(receivers) >= 2 else "local",
                "status": "inconsistent" if errors else "locally_consistent",
                "unresolved_references": unresolved,
                "declaration": process.model_dump(mode="json"),
            }
        )
    return {
        "policy": POLICY,
        "status": "incomplete" if items else "ready",
        "blocking_items": [i["id"] for i in items],
        "items": items,
        "processes": processes,
        "shared_declarations": sum(p["scope"] == "shared" for p in processes),
        "local_declarations": sum(p["scope"] == "local" for p in processes),
        "deferred": "Unknown references, algebraic cycles, required pathways and "
        "consumer assembly are checked on the complete topology. Local checks "
        "do not certify scientific meaning, conservation, or mechanism recovery.",
    }


def topology_editing(draft: ledger.Draft) -> dict:
    """Display exact identifiers and possible corrections, never apply renamings."""
    defined = {e.name for e in draft.equations}
    variables = {v.name: v.definition for v in draft.variables}
    processes = {p.name for p in draft.processes}
    aliases = []
    for equation in draft.equations:
        if equation.name in variables or equation.name in processes:
            continue
        candidates = [
            name
            for name, definition in variables.items()
            if definition == "differential"
            and equation.name in {f"d{name}_dt", f"d_{name}"}
        ]
        if candidates:
            aliases.append(
                {
                    "returned_name": equation.name,
                    "possible_state_names": candidates,
                    "action": "If this is a derivative label for one of these "
                    "states, replace its topology under that exact state name "
                    "and remove the old entry with remove_equations. Otherwise "
                    "explicitly declare the intended new quantity. No automatic "
                    "name substitution has been performed.",
                    "remove_old_label_if_renaming": {
                        "remove_equations": [equation.name]
                    },
                }
            )
    consumers = {u.target for p in draft.processes for u in p.uses}
    return {
        "identifiers": IDENTIFIERS,
        "generated_variable_names": sorted(variables),
        "possible_derivative_label_mismatches": aliases,
        "ordinary_topology": EMPTY_ORDINARY,
        "pending_process_consumers": [
            {
                "name": name,
                "if_no_other_contributions": {"name": name, "terms": []},
                "meaning": "Proposer decision: return this only if the declared "
                "process uses cover all intended contributions. Otherwise supply "
                "the complete remaining ordinary list.",
            }
            for name in sorted(consumers & variables.keys() - defined)
        ],
    }
